// permissions.js
export const PERMISSIONS = {
  Sales: {
    overView: true,
    userBase: true,
    subscription: true,
    transaction: true,
    supportTicket: false,
    withdrawal: false,
    subcategory: true,
    store: true,
  },
  Finance: {
    overView: true,
    userBase: true,
    subscription: true,
    transaction: true,
    supportTicket: false,
    withdrawal: true,
    subcategory: false,
    store: false,
  },
  Product: {
    overView: true,
    userBase: true,
    subscription: true,
    transaction: true,
    supportTicket: true,
    withdrawal: true,
    subcategory: true,
    store: true,
  },
  CustomerCare: {
    overView: true,
    userBase: true,
    subscription: true,
    transaction: true,
    supportTicket: true,
    withdrawal: false,
    subcategory: true,
    store: true,
  },
  Brand: {
    overView: true,
    userBase: true,
    subscription: false,
    transaction: false,
    supportTicket: false,
    withdrawal: false,
    subcategory: true,
    store: true,
  },
  DataAnalyst: {
    overView: true,
    userBase: true,
    subscription: false,
    transaction: false,
    supportTicket: false,
    withdrawal: false,
    subcategory: true,
    store: true,
  },
  Admin: {
    overView: true,
    userBase: true,
    subscription: true,
    transaction: true,
    supportTicket: true,
    withdrawal: true,
    subcategory: true,
    store: true,
  },
};
